export {default as Home} from './Home'
export {default as Borrow} from './Borrow'
export {default as AddExpenses} from './AddExpenses'
export {default as History} from './History'
export {default as Slash} from './Slash'
export {default as Report} from './Report'